base: /
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ''
    flag: us
  -
    title: Spanish
    enabled: true
    languageId: 1
    base: /es
    typo3Language: es
    locale: es_ES.UTF-8
    iso-639-1: es
    navigationTitle: Español
    hreflang: es
    direction: ''
    flag: es
    fallbackType: strict
    fallbacks: ''

rootPageId: 1
websiteTitle: 'Tax Office of La Pared'
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=10'
routeEnhancers:
  -
    type: PageType
    default: '/'
    index: ''
    map:
      /: 0
      sitemap.xml: 1533906435
dependencies:
  - jacuzzi/psi
