psi:
  entrypoints:
    mainnavigation: 1
    footernavigation: 12
  pageIds:
    searchresult: 37
  breakpoints:
    desktop:
      media: '(min-width: 1200px)'
      width: '1900'
    tablet:
      media: '(min-width: 768px)'
      width: '992'
    mobile:
      media: '(min-width: 576px)'
      width: '768'
