base: /
dependencies:
  - jacuzzi/psi
languages:
  -
    title: English
    enabled: true
    locale: en_US
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: ''
    flag: us
    languageId: 0
rootPageId: 1
websiteTitle: ''
